Initial codebase commit
eclipse-uprotocol/uprotocol-kotlin pull request #1
Opened 2023-11-10 18:35 UTC by neelam-kushwah

Aligned Kotlin SDK with Java SDK, added Dokka plugin for Kotlin documentation, and integrated Eclipse Dash License for dependency license summaries.

2023-11-13 16:01 UTC, mikaelperrin requested changes
I would recommend removing the nullability for many of the value types, method arguments and method return types in the patch. In addition, java Optional is not really needed in kotlin and should be replaced with nullability (i.e. `Optional<String>` becomes `String?`

2023-11-13 16:10 UTC, neelam-kushwah commented on src/main/kotlin/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactory.kt
> +                .withSource(URI.create(source!!)) /* Not needed:
I agree. Currently, I am working on removing the non-null assertion operator from all classes and will only keep it when necessary.

2023-11-13 17:50 UTC, neelam-kushwah commented on src/main/kotlin/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactory.kt
> +        ): CloudEvent? {
Addressed the review comments. Ready for further review.

2023-11-13 17:51 UTC, neelam-kushwah commented on src/main/kotlin/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactory.kt
> +                .withSource(URI.create(source!!)) /* Not needed:
Addressed the review comments. Ready for further review.

2023-11-15 00:26 UTC, stevenhartley approved these changes

2023-11-15 00:57 UTC, stevenhartley commented
Merging the initial release so that we can workout the workflows and last minute 1.5 changes.

2023-11-15 00:57 UTC, merged

2023-11-16 13:48 UTC, mikaelperrin reviewed
Although this PR is closed, there is still some java-like code that we may want to convert to kotlin.

2023-11-16 13:56 UTC, mikaelperrin reviewed
CompletableFuture usage is an issue here. We should think of leveraging async features from kotlin instead.

2023-11-16 13:56 UTC, mikaelperrin commented on src/main/kotlin/org/eclipse/uprotocol/rpc/RpcMapper.kt
> +            responseFuture: CompletableFuture<UPayload>,
should we consider coroutines here (i.e. kotlin flow or suspendable functions)? CompletableFuture is the java async type.

2023-11-16 14:47 UTC, neelam-kushwah commented on src/main/kotlin/org/eclipse/uprotocol/transport/datamodel/UPayload.kt
> +    }
After converting the class to a data class, a warning is generated due to the presence of a property with an 'Array' type. It is advised to override the 'equals()' and 'hashCode()' methods to ensure proper functionality when comparing instances of the data class.

2023-11-16 15:04 UTC, neelam-kushwah commented on src/main/kotlin/org/eclipse/uprotocol/transport/datamodel/UStatus.kt
> +            fun from(value: Int): Optional<Code> {
If we replace "optional" with "nullable," the property will return either a value or null. However, it's important to note that we don't want to return null. To confirm whether this change is appropriate or not, I suggest @stevenhartley provide input here

2023-11-16 15:30 UTC, neelam-kushwah commented on src/main/kotlin/org/eclipse/uprotocol/transport/builder/UAttributesBuilder.kt
> +            Objects.requireNonNull(priority, "UPriority cannot be null.")
Addressed comments; ready for further review. New pull request created.

2023-11-16 15:30 UTC, neelam-kushwah commented on src/main/kotlin/org/eclipse/uprotocol/transport/builder/UAttributesBuilder.kt
> +            Objects.requireNonNull(sink, "sink cannot be null.")
Addressed comments; ready for further review. New pull request created.

2023-11-16 15:30 UTC, neelam-kushwah commented on src/main/kotlin/org/eclipse/uprotocol/transport/datamodel/UPayload.kt
> +        this.data = Objects.requireNonNullElse(data, ByteArray(0))
Addressed comments; ready for further review. New pull request created.

2023-11-16 15:30 UTC, neelam-kushwah commented on src/main/kotlin/org/eclipse/uprotocol/transport/datamodel/UStatus.kt
> +                return Arrays.stream(entries.toTypedArray()).filter { p: Code -> p.value() == value }.findAny()
Addressed comments; ready for further review. New pull request created.

2023-11-16 15:31 UTC, neelam-kushwah commented on src/main/kotlin/org/eclipse/uprotocol/transport/datamodel/UPayload.kt
> +    }
Addressed comments; ready for further review. New pull request created.